language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
install:
  - pip install --user git+https://github.com/pmla/auguste
# command to run tests
script:
  - pytest tests/*
